<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlledVocabulary\ControlledVocabulary.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharpAux" Version="[2.0.0]" />
    <PackageReference Include="Graphoscope" Version="[0.6.0-preview.1]" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="TypeProviderDeps\ProvidedTypes.fsi" />
    <Compile Include="TypeProviderDeps\ProvidedTypes.fs" />
    <Compile Include="GraphoscopeAux.fs" />
    <Compile Include="ImportAux.fs" />
    <None Include="obo\README.md" />
    <Compile Include="OBO\DBXRef.fs" />
    <Compile Include="OBO\TermSynonym.fs" />
    <Compile Include="OBO\OboTerm.fs" />
    <Compile Include="OBO\OboTypedef.fs" />
    <Compile Include="OBO\OboEntry.fs" />
    <Compile Include="OBO\OboEntries.fs" />
    <Compile Include="OBO\OboOntology.fs" />
    <Compile Include="OBO\OboProvider.fs" />
    <Compile Include="OntologyRelation.fs" />
    <Compile Include="Ontology.fs" />
  </ItemGroup>

  <ItemGroup />

  <PropertyGroup>
    <Authors>Heinrich Lukas Weil, Oliver Maus, F# open source contributors</Authors>
    <Description>A library to work with ontologies and ontology-related file formats.</Description>
    <Summary>A library to work with ontologies and ontology-related file formats.</Summary>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>ontology parser obo</PackageTags>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
