<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ControlledVocabulary\ControlledVocabulary.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharpAux" Version="[2.0.0]" />
    <PackageReference Include="ARCtrl.Core" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="OBO\DBXref.fs" />
    <Compile Include="OBO\TermSynonym.fs" />
    <Compile Include="OBO\OboTerm.fs" />
    <Compile Include="OBO\OboTypeDef.fs" />
    <Compile Include="OBO\OboOntology.fs" />
    <Compile Include="OBO\OboParser.fs" />
    <Compile Include="SynonymContext.fs" />
  </ItemGroup>

  <PropertyGroup>
    <Authors>Heinrich Lukas Weil, Oliver Maus, F# open source contributors</Authors>
    <Description>A library to work with ontologies and ontology-related file formats.</Description>
    <Summary>A library to work with ontologies and ontology-related file formats.</Summary>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>ontology parser obo</PackageTags>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
